sudo: true
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - strongswan
      - xl2tpd
install: pip install tox-travis
before_script:
  - >
    cat > /etc/ipsec.conf <<EOF
    config setup
    conn %default
      ikelifetime=60m
      keylife=20m
      rekeymargin=3m
      keyingtries=1
      keyexchange=ikev1
      authby=secret
      ike=aes128-sha1-modp1024,3des-sha1-modp1024!
      esp=aes128-sha1-modp1024,3des-sha1-modp1024!

    conn myvpn
      keyexchange=ikev1
      left=%defaultroute
      auto=add
      authby=secret
      type=transport
      leftprotoport=17/1701
      rightprotoport=17/1701
      right=$VPN_SERVER_IP
    EOF
  - >
    cat > /etc/ipsec.secrets <<EOF
    : PSK "$VPN_IPSEC_PSK"
    EOF
  - >
    chmod 600 /etc/ipsec.secrets
  - >
    cat > /etc/xl2tpd/xl2tpd.conf <<EOF
    [lac myvpn]
    lns = $VPN_SERVER_IP
    ppp debug = yes
    pppoptfile = /etc/ppp/options.l2tpd.client
    length bit = yes
    EOF
  - >
    cat > /etc/ppp/options.l2tpd.client <<EOF
    ipcp-accept-local
    ipcp-accept-remote
    refuse-eap
    require-chap
    noccp
    noauth
    mtu 1280
    mru 1280
    noipdefault
    defaultroute
    usepeerdns
    connect-delay 5000
    name $VPN_USER
    password $VPN_PASSWORD
    EOF
  - >
    chmod 600 /etc/ppp/options.l2tpd.client
  - >
    mkdir -p /var/run/xl2tpd
    touch /var/run/xl2tpd/l2tp-control
  - >
    service strongswan restart
    service xl2tpd restart
  - >
    ipsec up myvpn
    echo "c myvpn" > /var/run/xl2tpd/l2tp-control
script: tox
after_script:
  - >
    echo "d myvpn" > /var/run/xl2tpd/l2tp-control
    ipsec down myvpn
notifications:
    email: false